server:
  port: 8501

spring:
  application:
    name: account-service


spcloud:
  cassandra:
    port: 9042
    contact:
      point: localhost
    keyspace:
      name: springcloud
    password: cassandra
    username: cassandra