server:
  port: 8501

spring:
  application:
    name: account-service

# register to eureka server as a client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spcloud:
  cassandra:
    port: 9042
    contact:
      point: localhost
    keyspace:
      name: springcloud
    password: cassandra
    username: cassandra