server:
  port: 8503

spring:
  application:
    name: notification-service
  rabbitmq:
    username: muhammedtopgul
    password: muhammedtopgul
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue

# register to eureka server as a client
eureka:
  client:
    # register-with-eureka: false #default true
    # fetch-registry: true #default true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/