server:
  port: 8502

spring:
  application:
    name: ticket-service
  # mysql config
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: muhammedtopgul
    password: muhammedtopgul
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue

# register to eureka server as a client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/