server:
  port: 8502

spring:
  application:
    name: ticket-service
  # mysql config
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    hibernate:
      ddl-auto: update

# register to eureka server as a client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/